import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans_KR } from '@next/font/google'

export const metadata: Metadata = {
  title: 'JPTest - LeeSungjin',
  description: 'Generated by create next app',
}

const notoSansKR = Noto_Sans_KR({
  weight: ['400', '700'],
  display: 'swap',
  preload: false
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko" className={notoSansKR.className}>
      <body>{children}</body>
    </html>
  )
}
